version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - WEBSOCKET_HOST=0.0.0.0
      - WEBSOCKET_PORT=7860
    volumes:
      - ./backend:/app
    networks:
      - maurice-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - maurice-network

networks:
  maurice-network:
    driver: bridge