[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python backend/server.py"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[environments.production]
[environments.production.variables]
WEBSOCKET_HOST = "0.0.0.0"
LOG_LEVEL = "INFO"
PYTHONUNBUFFERED = "1"